### ISSUE TITLE
[Task]: Admin can Crud Listing Space Types

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-frontend#1]
### Task Summary

Admin can create, update and delete listing space types from web client

### Acceptance criteria

- [ ] Admin can create listing space type
- [ ] Admin can view list of created types
- [ ] Admin can update types
- [ ] Admin can delete types
- [ ] Admin can make types active or inactive

### Scenario

From System dashboard, admin can create listing space types. Types can be active or inactive. If inactive they will not be available to the client to select (or will be disabled for selection)
