### ISSUE TITLE
[Task]: Admin can crud listing purposes

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-frontend#10]
### Task Summary

Admin can configure listing purpose settings

### Acceptance criteria

- [ ] Admin can view listing purposes
- [ ] Admin can create new listing purposes
- [ ] Admin can edit listing purposes
- [ ] Admin can delete listing purposes
- [ ] Admin can view subgroups
- [ ] Admin can create new subgroups
- [ ] Admin can edit subgroups
- [ ] Admin can delete subgroups

### Scenario

Admin can set purpose and subgroup settings for users to select from when creating a listing.
