### ISSUE TITLE
[Task]: Admin Layout

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-frontend#14]
### Task Summary

Admin Layout

### Acceptance criteria

- [ ] Admin layout should have it's own Side bars
- [ ] Admin layout should have it's own header
- [ ] Admin layout should have it's own navigation links
- [ ] Should only be accessible to Admin and admin related roles

### Scenario

When an admin user wants to access the admin section, there should be a link on the regular app that allows admins to do so. The admin section should have it's own layout with links to different sections of the app for admins to manage

### Any Additional Context

Admin layout should have links for admins to manage resources including (but not limited to):
- Users (for managing devices, user accounts, adding / removing roles etc)
- User profiles (i.e. following, followers, blocking, etc)
- Content moderation (reviewing, approving / rejecting content publishing etc)
- Listings (for approvals, editing, creating on behalf of, host assistance etc)
- Managing communications (email templates, sms templates, sending emails & sms etc)
- Managing Transactions (analytics, general accounting, refunds, fraud detection etc)
- Managing Services
- Managing Support Tickets
- Managing Application Settings (listing settings, post settings, service settings, location settings etc)
- Managing & publishing Application wide notifications, alerts, etc.
