### ISSUE TITLE
[Task]: Admin can Crud Listing Amenities

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-frontend#2]
### Task Summary

Admin can Crud listing amenities

### Acceptance criteria

- [ ] Admin can create Amenity Categories
- [ ] Admin can view list of amenity categories
- [ ] Admin can update amenity category
- [ ] Admin can delete amenity category
- [ ] Admin can create Amenity
- [ ] Admin can view list of Amenities
- [ ] Admin can update Amenity
- [ ] Admin can delete Amenity

### Scenario

From System dashboard, admin can create amenity categories, and amenities. They can be active or inactive. If inactive they will not be available to the client to select (or will be disabled for selection)
