### ISSUE TITLE
[Task]: Admin can Crud Listing House Rules

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-frontend#3]
### Task Summary

Admin can Crud Listing House Rules

### Acceptance criteria

- [ ] Admin can create House rule
- [ ] Admin can view list of house rules
- [ ] Admin can update a house rule
- [ ] Admin can delete a house rule

### Scenario

From System dashboard, admin should be able to create and manage house rules. House rules will be available to user to add more information about a listing when creating or updating
