### ISSUE TITLE
[Task]: Get suggested profiles

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-frontend#6]
### Task Summary

Get suggested profiles

### Acceptance criteria

- [ ] Guests will be presented with popular / promoted profiles
- [ ] Users will be presented with relevant profiles to follow
- [ ] Decide suggested profile priority (promoted, popular, relevant)

### Scenario

When a visitor lands on the site, they should be presented with profiles to follow
If the user is logged in, then more relevant profiles should be presented (based on location, promotions, recently viewed etc)
